using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace JsonSerializerGenerators;

public static class SourceGenerationHelpers
{
    public const string ObjectLevelAttribute = """
                                               namespace JsonSerializerGenerators;
                                               [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                                               public class SourceJsonSerializableAttribute : Attribute { }
                                               """;

    public const string FieldLevelAttribute = """
                                              namespace JsonSerializerGenerators;
                                              [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
                                              public class SourceJsonIgnoreFieldAttribute : Attribute { }
                                              """;

    public static string GeneratePartialClass(ClassDeclarationSyntax syntaxNode)
    {
        var className = syntaxNode.Identifier.Text;
        return $$"""
                    // <auto-generated />
                    public partial class {{className}}
                    {
                        public string ToJson() => "{ "message": "Hello from the generator!" }";
                    }
               """;
    }
}